language: go

go:
  - 1.12.x

os:
  - linux
  - osx

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - main

addons:
  sonarcloud:
    organization: "xmidt-org"
    token:
      secure: "xx"


script:
  - make style codecov

after_success:
  - sonar-scanner -Dproject.settings=./.sonar-project.properties

jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - make it
